# Java Gradle CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2.1

aliases:
  - &downstream_builds
    name: Trigger downstream builds
    command: |
      echo 'export CIRCLE_API_TOKEN="$CIRCLE_API_USER_TOKEN"' >> $BASH_ENV
      /tools/downstream_single_trigger.sh "bitbucket/enturas/abt-core" "develop"
      /tools/downstream_single_trigger.sh "bitbucket/enturas/abt-referencedata" "develop"
      /tools/downstream_single_trigger.sh "bitbucket/enturas/abt-inspection-lib" "develop"

  - &sonar-scan
    name: Sonar
    command: |
      mvn sonar:sonar \
        -Dsonar.projectKey=enturas_${CIRCLE_PROJECT_REPONAME} \
        -Dsonar.organization=${SONAR_ORG} \
        -Dsonar.projectName=${CIRCLE_PROJECT_REPONAME} \
        -Dsonar.host.url=https://sonarcloud.io \
        -Dsonar.login=${ENTUR_SONAR_PASSWORD}
  - &release
      name: Release
      command: |
        OLD_VERSION=$(mvn -q \
          -Dexec.executable="echo" -Dexec.args='${project.version}' \
          --non-recursive org.codehaus.mojo:exec-maven-plugin:1.6.0:exec)
        NEW_VERSION="${OLD_VERSION/-SNAPSHOT/}"
        echo "Releasing $OLD_VERSION as $NEW_VERSION"

        mvn versions:use-releases

        mvn versions:set -DnewVersion="$NEW_VERSION"
        git add pom.xml
        git commit -m "release: $NEW_VERSION"
        git push origin master
        echo "Pushed $NEW_VERSION to master"

        MAJ_VERSION=$(echo "$NEW_VERSION" | cut -d '.' -f 1)
        MIN_VERSION=$(echo "$NEW_VERSION" | cut -d '.' -f 2)
        NEW_MINOR=$(($MIN_VERSION + 1))
        DEV_VERSION="$MAJ_VERSION.$NEW_MINOR-SNAPSHOT"

        git checkout develop
        git merge --no-edit master
        mvn versions:set -DnewVersion="$DEV_VERSION"
        git add pom.xml
        git commit -m "ready for development: $DEV_VERSION"
        git push origin develop
        echo "Pushed $DEV_VERSION to develop"


  - &maven-settings-file
      "\"<settings xsi:schemaLocation='http://maven.apache.org/SETTINGS/1.1.0 http://maven.apache.org/xsd/settings-1.1.0.xsd' xmlns='http://maven.apache.org/SETTINGS/1.1.0'
            xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'>
          <servers>
            <server>
              <username>$entur_artifactory_user</username>
              <password>$entur_artifactory_password</password>
              <id>central</id>
            </server>
            <server>
              <username>$entur_artifactory_user</username>
              <password>$entur_artifactory_password</password>
              <id>snapshots</id>
            </server>
          </servers>
          <profiles>
      <profile>
        <repositories>
          <repository>
            <snapshots>
              <enabled>false</enabled>
            </snapshots>
            <id>central</id>
            <name>entur-team-kontobasert-billettering-release</name>
            <url>https://entur2.jfrog.io/entur2/entur-team-kontobasert-billettering-release</url>
          </repository>
          <repository>
            <snapshots />
            <id>snapshots</id>
            <name>entur-team-kontobasert-billettering-snapshot</name>
            <url>https://entur2.jfrog.io/entur2/entur-team-kontobasert-billettering-snapshot</url>
          </repository>
        </repositories>
        <pluginRepositories>
          <pluginRepository>
            <snapshots>
              <enabled>false</enabled>
            </snapshots>
            <id>central</id>
            <name>entur-team-kontobasert-billettering-release</name>
            <url>https://entur2.jfrog.io/entur2/entur-team-kontobasert-billettering-release</url>
          </pluginRepository>
          <pluginRepository>
            <snapshots />
            <id>snapshots</id>
            <name>entur-team-kontobasert-billettering-snapshot</name>
            <url>https://entur2.jfrog.io/entur2/entur-team-kontobasert-billettering-snapshot</url>
          </pluginRepository>
        </pluginRepositories>
        <id>artifactory</id>
      </profile>
          </profiles>
          <activeProfiles>
            <activeProfile>artifactory</activeProfile>
          </activeProfiles>
        </settings>\""


  - &java-container-config
    docker:
      - image: circleci/openjdk:11-jdk

  - &circleci-container-config
    docker:
      - image: eu.gcr.io/carbon-1287/circleci-toolbox-image
        auth:
          username: _json_key
          password: $GCLOUD_SERVICE_KEY


commands:
  generate-maven-settings-file:
    parameters:
      settings-file:
        type: string
    steps:
      - run:
          name: Generate Maven Settings File
          command: |
            mkdir -p ~/.m2
            echo -e << parameters.settings-file >> > ~/.m2/settings.xml
  send-slack-message:
    parameters:
      payload:
        type: string
    steps:
      - run:
          name: Sending message to Slack
          command: |
            curl -X POST -H 'Content-type: application/json' --data << parameters.payload >> $SLACK_WEBHOOK

jobs:
  build:
    <<: *java-container-config
    environment:
      MAVEN_OPTS: -Xmx1024m

    steps:
      - checkout

      - restore_cache:
          keys:
            - cache-dependencies-{{ checksum "pom.xml" }}
            - cache-dependencies-abt-referencedata-11012019

      - generate-maven-settings-file:
          settings-file: *maven-settings-file

      - run: mvn clean verify

      - save_cache:
          paths:
            - ~/.m2
          key: cache-dependencies-{{ checksum "pom.xml" }}

      - persist_to_workspace:
          root: ../
          paths:
            - project
            - .m2

      - store_artifacts:
          path: target/dependency-check-report.html

      - store_artifacts:
          path: target/dependency-check-vulnerability.html

  postBuild:
    <<: *circleci-container-config

    steps:
      - run: *downstream_builds

  sonar:
    <<: *java-container-config
    steps:
      - attach_workspace:
          at: ../
      - restore_cache:
          keys:
            - cache-dependencies-{{ checksum "pom.xml" }}
            - cache-dependencies-18012019

      - run: *sonar-scan

  deploy:
    <<: *java-container-config
    steps:
      - attach_workspace:
          at: ../
      - restore_cache:
          keys:
            - cache-dependencies-{{ checksum "pom.xml" }}
            - cache-dependencies-18012019

      - run: mvn deploy -DskipTests

  release:
    <<: *java-container-config
    steps:
      - checkout
      - attach_workspace:
          at: ../
      - restore_cache:
          keys:
            - cache-dependencies-{{ checksum "pom.xml" }}
            - cache-dependencies-18012019
      - run: *release


workflows:
  version: 2
  nightly-sonar-analysis:
    triggers:
      - schedule:
          cron: "0 2 * * *"
          filters:
            branches:
              only: develop
    jobs:
      - build:
          context: org-default-build
      - sonar:
          context: global
          requires:
            - build
  main:
    jobs:
      - build:
          context: org-default-build
          filters:
            branches:
              only:
              - master
              - develop
      - postBuild:
          context: org-carbon
          requires:
            - build
          filters:
            branches:
              only: develop
      - release:
          context: org-default-build
          requires:
            - build
          filters:
            branches:
              only: master
      - deploy:
          context: org-carbon
          requires:
            - release
            - build
          filters:
            branches:
              only:
              - develop
              - master